name = "Fizaan Ali Shafiq Mughal"
print(len(name))
print(name.endswith("al"))
print(name.startswith("fizaan"))
print(name.lower())
print(name.upper())
print(name.capitalize())
print(name.count("a"))
print(name.replace("Fizaan", "Ali"))
print(name.find("Shafiq"))
print(name.index("Shafiq"))
print(name.isalnum())
print(name.isalpha())
print(name*3)
print(name) 
print(name.split(" "))
print(name.isalpha())
print("Fizaan".isalpha())
print("My name is {} and I am {} years old".format(name, 17))